apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-svc
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  type: ClusterIP
